[package]
name = "vtk-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte-order = "0.3.0"
nalgebra = { version="0.32.2" }
